# Generated by Django 5.2.7 on 2025-10-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_format_valid', models.BooleanField(default=False)),
                ('has_mx', models.BooleanField(default=False)),
                ('smtp_valid', models.BooleanField(default=False)),
                ('spf', models.BooleanField(default=False)),
                ('dkim', models.BooleanField(default=False)),
                ('dmarc', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
